### ISSUE TITLE
BeginDialogue not pushing to client in UE 5.1

### ISSUE THREAD

**Issue by ocdframeworks** [ReubenW/Narrative#10]
![image](https://user-images.githubusercontent.com/90984792/212502736-77abe191-2a40-4638-bced-4abaef19fbd7.png)
![image](https://user-images.githubusercontent.com/90984792/212502725-2a27497c-681d-4f76-9284-e46b073035d2.png)
When calling begin dialogue on server to feed to client, client never receives dialogue. 
this behavior works in versions 5.0 and lower, but seems to have broken in the latest version.
Posting pictures of sample blueprint. Same in both engines, however produces bug in 5.1

**Comment by ReubenW** [comment]
Not encountering this issue on my end, are you sure your logic is being called by adding a breakpoint?

**Comment by ocdframeworks** [comment]
@ReubenW This was figured out in the discord at the beginning of 2023, you provided the correct code for us to fix the issue in the plug-in
