### ISSUE TITLE
Inheriting from DialogueNode_NPC crashes on open

### ISSUE THREAD

**Issue by d3kryption** [ReubenW/Narrative#11]
Error raised by StyX92 in the Discord and posted by me (StyX92 gave me permission) :D 

Mp4 attached.

# Steps to reproduce:
1 - Open Content Drawer
2 - Right click -> create Blueprint
3 - Select the parent class as DialogueNode_NPC
4 - Name the file
5 - Try to open the file

# Error:
```
LoginId:c5a5fb434e4d10c904fef2bcc815aa64
EpicAccountId:35ce0abcb0274b4f943091be4f5326c7

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000028

UnrealEditor_NarrativeDialogueEditor!FDialogueEditorDetails::CustomizeDetails() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\Narrative\Source\NarrativeDialogueEditor\Private\DialogueEditorDetails.cpp:74] 
```

# Line in code:
DialogueEditorDetails.cpp:74

```
if (UDialogueBlueprint* DialogueBP = Cast<UDialogueBlueprint>(NPCNode->OwningDialogue->GetOuter()))
```

# Versions
Unreal 5.0.3

Confirmed an issue by D3ryption for Unreal 5.1 and Narrative 2.6.0

Hope this helps :)

# Video
https://user-images.githubusercontent.com/48034534/213858834-b52c3897-0e12-41dd-9258-b4250ff97d8f.mp4

**Comment by ReubenW** [comment]
This has now been fixed and the fix will be in the next release, thanks for the report.
