### ISSUE TITLE
Narrative Default UI - Visible by default

### ISSUE THREAD

**Issue by d3kryption** [ReubenW/Narrative#12]
Hey,

Minor issue, very minor but I feel it does count as a bug? (happy if you don't feel the same :) )

On BP_NarrativeDefaultUI there is a CanvasPanel that is set to Non hit by default (on game load).

But on any dialogue finish, its set to hidden.

I've added a profile picture box and its visible at the start. After playing dialogue, it hides away.

# Steps to resolve
- Open BP_NarrativeDefaultUI
- Click the DialogueUI canvas panel in the Hierarchy
- Set the visibility under Behavior to Hidden

Very minor one but might stop the odd error :) 

Thanks

- Dan

**Comment by ReubenW** [comment]
Thanks for the report, now fixed and will be in the next release.
