### ISSUE TITLE
warning C4996: 'IAssetRegistry::GetAssetsByClass'

### ISSUE THREAD

**Issue by lehuan5062** [ReubenW/Narrative#13]
`NarrativeTaskManager.cpp(31): warning C4996: 'IAssetRegistry::GetAssetsByClass': Class names are now represented by path names. Please use a version of this function that uses FTopLevelAssetPath. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.`

I have this issue when I compile with the shipping setting.

**Comment by ReubenW** [comment]
This won't effect you packaging and is just a warning - I did attempt to fix this but documentation on FTopLevelAssetPath is really minimal and I can't figure out how to get the class path just yet.

I will have this fixed eventually but is not super top priority!

**Comment by philboltt** [comment]
`AssetRegistryModule.Get().GetAssetsByClass(UNarrativeTask::StaticClass()->GetClassPathName(), AssetData);`

**Comment by ReubenW** [comment]
> 

Thanks, where did you learn that! Appreciate the help. This will be fixed now thanks to @philboltt :)

**Comment by philboltt** [comment]
Engine source (definitely not docs, lol).  Got blasted by warnings on a project I was working on.

**Comment by lehuan5062** [comment]
> definitely not docs, lol

I'm not sure why they haven't documented their engine properly, or we might have to use Epic premium support service for that.
