### ISSUE TITLE
Pressing B or Esc while in the collision area of a character with the narrative plugin on them breaks the Main characters responses. 

### ISSUE THREAD

**Issue by Maturn77** [ReubenW/Narrative#14]
I can't believe I had to join stupid Github when, I emailed, Wrote and sent you a freaking new video. 2 minutes getting to the point proving my issue. At this point I doubt you will fix something so stupid and easy for you. When you press B or Esc in a box collision with any character that has the narrative plugin, it breaks. Now you can press B or esc at any other point and it won't mess this up. Only when you are about to have dialogue with another person. It will take you out of the dialogue like is suppose too. When you go back up to that character with the Narrative plugin, It won't show your main characters responses anymore. I found if you talk with another narrative dialogue character it can fix this is issue, but you can't expect players to have to go through all that. Surprising enough if they have audio it won't break this, only if the narrative dialogue character doesn't have a sound file on their dialogue. I am now just going to post the video here. I didn't want to go this route. Even let you know 4 weeks, or a month ago in the comments and your email privately. But here is the link so anyone can see what I am talking about. https://youtu.be/jo6ib-qI_BI You can clearly see that is an issue. I sent this privately and the author wrote me back in two weeks thought he was going to fix the issue. Turns out I have to write on here to get him to start on anything. Even though I sent him proof. I am a nice person, but I don't think you should have to go through this for someone to fix something. It would take him probably an hour or two lol.

**Comment by ReubenW** [comment]
Hi there Maturn!

I'm having a hard time reproducing the issue on my end. Can you please give me steps to repro this so I can get this fixed for you?

**Comment by Maturn77** [comment]
I have sent you a new video showing it. When you walk up to a person with the narrative plugin and they start to talk with you. You press b or esc the dialogue goes away like it suppose too. When you go back up to the character then the dialogue just stays on the first line. Your main character cannot respond after that point. The decisions won’t appear for you. I have a video showing this better https://youtu.be/jo6ib-qI_BI. Now if you have audio on the character then it seems to work regardless, It doesn’t matter if you press B or Esc any other point in the game. Only when you are in the characters collsion box that has the dialogue narrative part.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Maturn77** [comment]
I have sent you a new video showing it. When you walk up to a person with the narrative plugin and they start to talk with you. You press b or esc the dialogue goes away like it suppose too. When you go back up to the character then the dialogue just stays on the first line. Your main character cannot respond after that point. The decisions won’t appear for you. I have a video showing this better https://youtu.be/jo6ib-qI_BI. Now if you have audio on the character then it seems to work regardless, It doesn’t matter if you press B or Esc any other point in the game. Only when you are in the characters collsion box that has the dialogue narrative part.

**Comment by Maturn77** [comment]
I use my xbox controller mostly, but tested it on the keyboard event. Just watch the youtube video. It clearly shows it man. Over and over I show this issue.

**Comment by Maturn77** [comment]
The video shows you the steps over and over.

**Comment by Maturn77** [comment]
Have you checked it out? That video shows everything. It shows the issue in less than 5 minutes.

**Comment by Maturn77** [comment]
I am having Deja Vu. Why the hell write me like you are going to actually going to do something and then disappear? This is the same crap you did on our private emails pal. Wrote me something really quick just like this. I get a little shed of hope you are actually going to do something. Two weeks go by and you say write you on here, Github, to fix the probably you said you would fix over our emails lol.  I give you proof and just say help and the same thing. You don't write back, never watch the freaking video and don't write back. Geez, This crap has been over a month man. Same crap from you everytime. Whether it's on here, Youtube, epic. I seriously think you could fix this issue in five dang minutes if you would get your goofy looking head out of your ass and do it. You said I was spamming you lol. No you have not done a dang thing. After all this time. Okay maybe 10 minutes of your so precious time, and this would be fixed.

**Comment by Maturn77** [comment]
Should have known man. I wonder if these things he writes are just pre recorded since the wrote back so quickly and now magically so quiet.

**Comment by Maturn77** [comment]
I seriously think you might be the dumbest human being. I never at this point made it personal, but you lost that when you called me a spammer dickweed. You have a potentially great product that is broken as of now. You won't help, never watched the dang video I commented on here twice now with the link. What did you do, say show me the steps, with not looking at the video. I know that because I saw the view count.  Good job idiot. I have over 5 views on it on YouTube. The is specifically from your page on Epic. Hope none of them buy your crappy product until you fix this. One wrote me privately so keep it up moron! You will be probably lose sells out of stupidity. All that is on you. I am getting off this stupid thing. I knew you would be a waste of breathe. Good luck Scammer!

**Comment by Maturn77** [comment]
How many times have I sent you the video showing proof that your plugin has isues here for the 9th maybe 10th time now https://youtu.be/jo6ib-qI_BI. I seriously think you might be the dumbest human being. I never at this point made it personal, but you lost that when you called me a spammer dickweed. You have a potentially great product that is broken as of now. You won't help, never watched the dang video I commented on here twice now with the link. What did you do, say show me the steps, with not looking at the video. I know that because I saw the view count. Good job idiot. I have over 5 views on it on YouTube. The is specifically from your page on Epic. Hope none of them buy your crappy product until you fix this. One wrote me privately so keep it up moron! You will be probably lose sells out of stupidity. All that is on you. I am getting off this stupid thing. I knew you would be a waste of breathe. Good luck Scammer! You don’t have to worry about it I will release that video publicly soon. I am done trying with you. I written you on everything. You are a freaking SCAMMER. I don’t want to hear from you anymore. I don’t want to deal with you anymore. I will write epic about you doing this. Showing this by next week. I can you tell for a fact I have already had someone write me on Youtube about your crappy product. I will make sure people know of this. I am not threating nor care about working with you. You have the dang proof and continue to do NOTHING. DON’T you freaking write me about reproducing this one more freaking time. I won’t look at GitHub anymore. I am just going to leave this up. SCREW YOU you scammer. You are going to lose sales you could potentially have out of being a little fraudster prick. Why don’t you uh sign up on my discord or Github and write that down lol. Freaking worm.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ReubenW** [comment]
Maturn, when I ask for repro steps, I need you to detail how I can get the bug to occur on my end from a template project. For example:

_"Create a new project, and put a narrative component on the player controller. Add a sphere collision that begins a quest when overlapped. Notice that the quest won't start when the sphere is overlapped."_

This would be an example of repro steps. A 6 minute video of your game doesn't help me.

I have not been able to get the bug to occur on my end, and until you can provide clear repro steps (or send me a project where the bug is occurring in it) I cannot help.

**Comment by Maturn77** [comment]
I have told you and sent you two different videos showing the issue. Trust me I didn't want to blast out that about my game. I just wanted the issue fixed dude. I made that to show you it quicker as you requested. I know three people who mess with Unreal and two of them are making a game too. Guess what, this should be the easiest slam dunk for you, but you just keep ignoring the issue. The first vid was to show you the coding I have, and I have watched your videos multiple times to do this. You asked me in the private email to make it where you could clearly see the issue faster and not the coding. I did. That's this one which clearly says 2nd video. Look I can't do this dude. I write you like in  few minutes and you disappear for a day or weeks. Just stop. I had three people write me last night about your stupid product. So deal with it. I been trying to reach you over a month. On everything. You first say reach you on your email. I did that, then you say I have to reach you on Github. You write two quick little  response and disappear for a day on in. If you took what 30 minutes or an hour and get this fixed. I don't know how many times I have asked this out of you. Even said I would delete everything. Tell me one thing. Have you done that? Given me even 5 minutes over a month? Tell that to this Github. Tell that huh? I showed you in the last message and even explained it happened in a blank project on UE5 and I am using a kit for this one. So Seriously, I know you aren't going to fix this so please. Just stop. Don't write tomorrow or whenever you are going to pretend you are doing something. Deal with karma. You didn't watch the video out of how many times I sent it to you? I don't want to get excited or hopeful that you are going to do anything. I can probably guess you would have had two sells yesterday, but that's on your own stupidity. I know two people make actual games that would love a  working product, but you don't have it. I told one of them about an 10 dollar one that does most of your plugin, but it's only for UE5 and up. The only reason it sucks for me is that I have UE4 and migrating doesn't do to well on this one. I sell stuff of 3d as well. I have never just wrote a response and disappear for days or weeks. I always get the problem fixed. Usually within a day. YOU are obviously not like that. I am done hearing from you.  I have a kind of fix I found this morning, which is just put audio on everything even a piece of paper or the dialogue disappears when you press B. See there I did more investigating then the freaking author. It's still not a fix for the regular problem but I don't want to hear from you anymore. YOU have not done ANYTHING. I bet you didn't even look the issue up.

All you know how to do is TALK, no more either fix it or go away! I don't want to hear nothing more from you. I know you want to leave the last message like Oh I did something, but just once again ANSWER THIS. DID you even take two minutes out of the month and a couple days to help. DID YOU? That's what I thought. Anyone reading this. That' is what you get from Ole Reubs over here. Nothing.

________________________________

**Comment by ReubenW** [comment]
Closing this as Maturn77 has decided to create a new thread for this bug.

**Comment by Maturn77** [comment]
I updated my newer game to UE 5.4, can I get another copy of the Narrative Plugin version 3.3 or 3.4. I use the Narrative default UI still, so the newer versions mess with that to me. Thanks once again for your great product!
