### ISSUE TITLE
Player Dialogue Dissapears

### ISSUE THREAD

**Issue by Maturn77** [ReubenW/Narrative#15]
I have sent you a new video showing it. When you walk up to a person with the narrative plugin and they start to talk with you. You press b or esc the dialogue goes away like it suppose too. When you go back up to the character then the dialogue just stays on the first line. Your main character cannot respond after that point. The decisions won’t appear for you. I have a video showing this better https://youtu.be/jo6ib-qI_BI. Now if you have audio on the character then it seems to work regardless, It doesn’t matter if you press B or Esc any other point in the game. Only when you are in the characters collsion box that has the dialogue narrative part.

**Comment by ReubenW** [comment]
Hi Maturn, 

You need either repro steps from a template project or a link to a project with the bug occurring. Videos of the bug occurring in your project don't help me repro the bug on  my end.

**Comment by ReubenW** [comment]
Closed as maturn wasn't able to provide further details and I could reproduce the bug on my end.
