### ISSUE TITLE
Missing check causes hard crash

### ISSUE THREAD

**Issue by philboltt** [ReubenW/Narrative#16]
For my use case, it makes sense to have the NarrativeComponent on the GameState (all players share a common quest).  I've noticed that there's a problem in UDialogue::OnEnableDialogue_Implementation.  Where you're checking OldViewTarget you also check whether OwningController is valid, but you don't check OwningController when you check DialogueCameraShake.   Hard crash ensues.
![image](https://user-images.githubusercontent.com/1381611/225809278-c180d201-a8ac-4d5f-b04e-d2babc49bce7.png)

**Comment by ReubenW** [comment]
Thanks, will be fixed in next release.
