### ISSUE TITLE
In networked game, saved games don't preserve quest progress.

### ISSUE THREAD

**Issue by ennorehling** [ReubenW/Narrative#4]
To make this problem easy to reproduce, I built the following "minimal" project:

I added Narrative to the Third Person template, and implemented an NPC with the same behavior as Manny from the Stack-O-Bot example video (pick up 3 rocks, return them), with a few minor changes: Auto-saving is disabled, and so is save on exit. Instead, F2 will Save the game, and F3 will load it, for more control over when saving and loading happens. Saving and Loading only executes on the server, and I am playing in networked mode (Net Mode -> Play As Client).

This UE5 project can be downloaded at https://drive.google.com/file/d/1rr_yG_GdWWo64FP1LswLaia6P2TJYZ7W/view?usp=sharing 

To reproduce the bug:
* Get the quest from the "statue" NPC.
* Collect two rocks,
* Save game by pressing F2.
* Quit and restart.
* Load game by pressing F3.
* **Expected:** UI shows that I have collected 2/3 rocks.
* **Observed:** UI shows that I have collected 0/3 rocks.

**Comment by ReubenW** [comment]
The save system is currently only supported for single player games, but I would love to have it supported in networked games, especially as it seems like the system almost works in multiplayer already (just seems like quantities aren't correctly replicated?) I'm closing this for now but rest assured I will be looking into adding multiplayer save game support in the future.
